version: "3.4"
services:
    api:
        build:
            context: ./api
            network: host
        ports:
            - "8080:8080"
        volumes:
            - type: bind
              source: ./api
              target: /code
    frontend:
        build:
            context: ./frontend
        volumes:
            - type: bind
              source: ./frontend
              target: /app
            - type: volume
              source: nodemodules
              target: /app/node_modules
            - type: volume
              source: cache
              target: /app/.cache
            - type: volume
              source: parcelcache
              target: /app/.parcel-cache
        working_dir: /app
        ports:
            - 1234:1234
            - 1235:1235
volumes:
    nodemodules:
    cache:
    parcelcache:
