version: "3.4"
services:
    api:
        build:
            context: ./api
            network: host
        container_name: api
        ports:
            - "8080:8080"
            - "5001:5001"
        volumes:
            - type: bind
              source: ./api
              target: /code
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
    frontend:
        build:
            context: ./frontend
        volumes:
            - type: bind
              source: ./frontend
              target: /app
        working_dir: /app
        ports:
            - 1234:1234
            - 1235:1235
