version: "3.4"
services:
    api:
        image: encam_api:latest
        build:
            context: ./api
        volumes:
            - type: bind
              source: ./api
              target: /api_source
    encam-frontend-devel:
        image: encam_frontend:latest
        build:
            context: ./frontend
        volumes:
           - ./frontend:/app
        working_dir: /
    main:
      image: encam_main:latest
      build:
        context: ./
      ports:
            - "8080:8080"
            - "8443:8443"
            - "1235:1235"
      volumes:
          - type: bind
            source: ./api
            target: /api_source
          - type: bind
            source: ./config
            target: /config
