version: "3.4"
services:
    api:
        build:
            context: ./
            dockerfile: api/Dockerfile
            network: host
        ports:
            - 8080:8080
        volumes:
            - ./api:/code
    frontend:
        build:
            context: ./frontend
        volumes:
            - ./frontend:/app
            - /frontend/node_modules
            - /frontend/.parcel-cache
            - /frontend/.cache
        working_dir: /app
        ports:
            - 1234:1234
            - 1235:1235
