version: "3.4"
services:
    api:
        image: encam_api:latest
        build:
            context: ./api
            network: host
        volumes:
            - type: bind
              source: ./api
              target: /api_source
    frontend:
        image: encam_frontend:latest
        build:
            context: ./frontend
        volumes:
            - frontend-updates:/frontend_updates
            - type: bind
              source: ./frontend
              target: /frontend_source
        working_dir: /app
    main:
      build:
        context: ./
      ports:
            - "8080:8080"
            - "8443:8443"
      volumes:
          - frontend-updates:/frontend_updates
          - type: bind
            source: ./api
            target: /api_source
volumes:
  frontend-updates:
