version: "3.4"
services:
    api:
        build:
            context: ./api
            network: host
        ports:
            - "5000:5000"
        volumes:
            - type: bind
              source: ./api
              target: /code
