version: "3.4"
services:
    api:
        build:
            context: ./
            dockerfile: api/Dockerfile
            network: host
        container_name: api
        ports:
            - 5001:5001
        volumes:
            - ./api:/code
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - 80:80
    frontend:
        build:
            context: ./
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/build
            - /build/node_modules
            - /build/.parcel-cache
            - /build/.cache
        working_dir: /build
        ports:
            - 1234:1234
            - 1235:1235
