/**

  This is the fancy graphics with bodies buttons and graphs on the front page,
  slightly incorrectly referred to in the entire code base as the "Splash" page.
  Most of the code is in Center (generated by Bodies) and Domplots, but there is
  still a surprising amount of wiring to be done after those modules. So here goes...

*/
import * as React from 'react'

import {by} from './utils'
import * as utils from './utils'
import * as adhoc from './adhoc'

import type {SplashDB, SplashRow} from './SplashTypes'

import {Domplot, DomplotCSS, Legend} from './Domplot'

import {css} from 'emotion'

import * as backend from './backend'

import * as ui from './ui_utils'

import B_cells from './img/B_cells.png'
import CD4 from './img/CD4.png'
import CD4_Treg from './img/CD4_Treg.png'
import CD8 from './img/CD8.png'
import CD8_Treg from './img/CD8_Treg.png'
import M1 from './img/M1.png'
import M2 from './img/M2.png'
import NK from './img/NK.png'
import NKT from './img/NKT.png'
import mDC from './img/mDC.png'
import pDC from './img/pDC.png'
import iDC from './img/iDC.png'
import Myeloid_cell from './img/Myeloid.png'
import Granulocyte from './img/Granulocytes.png'

import * as c from './Center'

import {Dyn, useDyn} from './ui_utils/Dyn'

import {SectionInfo} from './Info'
// import {SectionInfo} from './Content'

const cell_pngs: Record<string, string> = {
  B_cells,
  CD4,
  CD4_Treg,
  CD8,
  CD8_Treg,
  M1,
  M2,
  NK,
  NKT,
  mDC,
  pDC,
  iDC,
  'Myeloid cell': Myeloid_cell,
  Granulocyte,
}

const left = 'MEL LUAD LUSC ESCA STAD KRCC BLCA PRAD'.split(' ')
const right = 'BRCA PPADpb PPADi COAD READ OVSA OVNSA UCEC'.split(' ')
const both = [...left, ...right]

// import {thief} from './thief'
const thief: undefined | ((cell: string, img: HTMLImageElement | null) => void) = undefined

interface State {
  type: 'cells' | 'tumors'
  selected: Record<string, boolean>
}

function review_state(state: State) {
  const tumors = utils.selected(state.type == 'tumors' ? state.selected : {})
  const cells = utils.selected(state.type == 'cells' ? state.selected : {})
  return {tumors, cells}
}

const state0: State = {
  type: 'cells',
  selected: {CD4: true},
}

function fixup_state(state: State): State {
  let sel_arr = utils.selected(state.selected)
  if (state.type === 'cells') {
    sel_arr = sel_arr.filter(cell => adhoc.cellOrder.includes(cell))
    sel_arr = utils.last(2, sel_arr)
  } else {
    sel_arr = sel_arr.filter(cell => !adhoc.cellOrder.includes(cell))
    sel_arr = utils.last(1, sel_arr)
  }
  return {
    type: state.type,
    selected: utils.createObject(
      sel_arr,
      k => k,
      () => true
    ),
  }
}

interface SplashProps {
  state: State
  set_state(s: State): void
  db?: SplashDB
  range?: utils.RowRange<SplashRow>
}

const classes = {
  Splash: css({
    ...ui.flex_row,
    '& > *': {
      flexShrink: 0,
      flexGrow: 0,
    },
    userSelect: 'none',
    '& label': {
      cursor: 'pointer',
    },
    '& h2': {
      margin: '10px auto',
      fontSize: '1.2em',
    },
  }),
  Left: css({
    ...ui.flex_column,
    width: 155,
    paddingLeft: 5,
  }),
  LeftLabel: css({
    ...ui.flex_row,

    border: '2px var(--cell-color) solid',
    borderRadius: 4,
    background: 'white',
    color: 'black',
    '&.Checked': {
      background: 'var(--cell-color)',
      color: 'white',
    },

    '& > *': {
      ...ui.flex_row,
      '& > *': {
        margin: 'auto',
      },
    },

    margin: '2px 0',
    padding: '3px 0',
    // sizes are adapted to iDC being 45 px (100%)
    height: 55,
    '& > .has-img': {
      width: 66,
      height: '100%',
      '& > img': {
        maxHeight: '100%',
      },
    },
    '& > .has-span': {
      flex: 1,
      '& > span': {
        textAlign: 'center',
        fontSize: '0.9em',
      },
    },
  }),
  Center: css({
    width: 750,
    marginTop: 40,
    minHeight: 680,
  }),
  CenterWithoutLegend: css`
    & .CenterLegend {
      display: none;
    }
  `,
  Right: css({
    ...ui.flex_column,
    borderLeft: '1px #ddd solid',
    paddingTop: 0,
    paddingLeft: 5,
    paddingRight: 5,
    overflowY: 'auto',
    overflowX: 'hidden',
    height: 900,
    width: 200,
    flex: '1 1 auto',
    '& > div': {
      marginBottom: 15,
      flexShrink: 0,
    },
  }),
}

function Checkboxes(
  range: string[],
  current: Record<string, boolean>,
  toggle: (value: string, checked: boolean) => void,
  color: (s: string) => string = () => 'black'
) {
  return range.map(x => {
    const checked = !!current[x]
    const onClick = () => toggle(x, !checked)
    return {
      checked,
      text: x,
      onClick,
      label: <label htmlFor={x}>{adhoc.pretty(x)}</label>,
      checkbox: (
        <span
          id={x}
          onClick={onClick}
          style={{
            borderRadius: '100px',
            border: `2px ${color(x)} solid`,
            background: checked ? color(x) : 'none',
            width: '12px',
            height: '12px',
            display: 'inline-block',
          }}
        />
      ),
    }
  })
}

function Center({state, set_state, db}: SplashProps) {
  const dyn = useDyn()

  return (
    <div
      className={classes.Center + ' ' + (state.type == 'cells' ? '' : classes.CenterWithoutLegend)}
      style={{display: 'flex'}}>
      <c.Center
        withTumor={(tumor: string, side: 'left' | 'right') => {
          const flexDirection = side === 'left' ? 'row-reverse' : 'row'
          const opp_side = side === 'left' ? 'right' : 'left'
          const plot_height = Math.round(dyn('plot height', 60, 20, 120))
          const {cells} = review_state(state)
          return (
            <div
              key={tumor}
              style={{
                gridArea: tumor,
                position: 'relative',
              }}>
              <div
                style={{
                  position: 'absolute',
                  [opp_side]: 0,
                  bottom: -dyn('label offset', 30, 0, 80),
                  display: 'flex',
                  flexDirection,
                  justifySelf: side == 'left' ? 'end' : 'start',
                  justifyContent: 'space-between',
                  alignSelf: 'end',
                  alignItems: 'flex-end',
                }}>
                <svg
                  width="20"
                  height="100"
                  style={{
                    position: 'absolute',
                    [side === 'left' ? 'left' : 'right']: '100%',
                    bottom: -9,
                    transform: side === 'right' ? 'scaleX(-1)' : undefined,
                    zIndex: 0,
                  }}>
                  <path
                    d={
                      tumor.match(/^(luad|esca|ppadpb|coad|ovsa)$/i)
                        ? 'M0 90 l6 6'
                        : tumor.match(/^(lusc|stad|ppadi|read|ovnsa)$/i)
                        ? 'M0 90 l6 -6 l0 -40'
                        : 'M0 90 l6 -6'
                    }
                    stroke="#aaa"
                    strokeWidth="2"
                    fill="none"
                  />
                </svg>

                <div
                  style={{
                    borderBottom: '2px #aaa solid',
                    margin: '0px 0px 0',
                    width: 80,
                    display: 'flex',
                    flexDirection,
                  }}>
                  <SectionInfo id={tumor} dir={opp_side} />
                  <span
                    style={{marginLeft: 2, marginRight: 2, cursor: 'pointer'}}
                    onClick={() => set_state({type: 'tumors', selected: {[tumor]: true}})}>
                    {tumor}
                  </span>
                </div>
                <div
                  style={{
                    borderBottom: '2px #aaa solid',
                    height: plot_height + 2 + 'px',
                  }}>
                  {!db || cells.length == 0 ? null : (
                    <Domplot
                      rows={db
                        .filter(row => state.selected[row.cell] && row.tumor == tumor)
                        .map(rename_row)}
                      kind="bar"
                      options={{
                        axis_right: side != 'left',
                        height: plot_height,
                        hulled: false,
                        x_axis: true,
                        max: Math.max(
                          ...db.filter(row => state.selected[row.cell]).map(row => row.expression)
                        ),
                      }}
                    />
                  )}
                </div>
              </div>
            </div>
          )
        }}
      />
    </div>
  )
}

const clsx = (...xs: any[]) => xs.filter(x => typeof x === 'string').join(' ')

const renames: Record<string, string> = {
  'Myeloid cell': 'Myeloid',
  Myeloid_cell: 'Myeloid',
  Granulocyte: 'Gran...',
}

const rename_row = (row: SplashRow): SplashRow => ({...row, cell: renames[row.cell] || row.cell})

function Left({state, set_state, range}: SplashProps) {
  return (
    <div className={classes.Left}>
      <h2>Cell type</h2>
      {range &&
        Checkboxes(
          adhoc.cellOrder.filter(cell => range.cell.includes(cell)),
          state.selected,
          (value, checked) =>
            set_state({type: 'cells', selected: {...state.selected, [value]: checked}}),
          adhoc.cell_color
        ).map((x, i) => {
          const cell = range.cell[i]
          const cell_png = cell_pngs[range.cell[i]]
          const img_props: React.ImgHTMLAttributes<HTMLImageElement> = thief
            ? {onLoad: e => thief(cell, e.target as any)}
            : {}
          const img = cell_png && <img src={cell_png} {...img_props} />
          const color = adhoc.cell_color(x.text)
          return (
            <label
              key={i}
              id={cell}
              htmlFor={cell}
              onClick={x.onClick}
              style={{'--cell-color': color} as any}
              className={clsx(classes.LeftLabel, x.checked && 'Checked')}>
              <div className="has-img">{img}</div>
              <div className="has-span">
                <span>{adhoc.pretty(cell)}</span>
                <div style={{marginRight: 0, marginLeft: 0}}>
                  <SectionInfo
                    id={
                      // "Myeloid cell" is sent from backend without underscore
                      cell.replace(/ /g, '_')
                    }
                  />
                </div>
              </div>
            </label>
          )
        })}
    </div>
  )
}

function Right({state, db}: SplashProps) {
  const out: React.ReactNode[] = []
  const legend = (backgroundColor?: string) => (
    <div
      style={{
        fontSize: 9,
        alignSelf: 'flex-end',
        marginTop: -4,
        marginRight: 5,
      }}>
      <Legend {...{backgroundColor}} />
    </div>
  )
  const forest_x = (
    <div
      style={{
        alignSelf: 'center',
        fontSize: 10,
        marginTop: -12,
        marginBottom: -10,
      }}>
      HR (95% CI)
    </div>
  )
  const bar_x = (
    <div
      style={{
        alignSelf: 'center',
        fontSize: 10,

        marginTop: -12,
        marginBottom: -10,
      }}>
      cells (1/mm²)
    </div>
  )

  if (db) {
    const {tumors, cells} = review_state(state)
    const opts = {
      orientation: 'portrait' as 'portrait',
      axis_right: true,
      height: 130,
      border_left: true,
    }
    for (const t of tumors) {
      out.push(<h2>{adhoc.pretty(t)} cell density</h2>)
      out.push(
        <Domplot
          rows={db.filter(row => row.tumor == t).map(rename_row)}
          kind="bar"
          options={opts}
        />
      )
      out.push(bar_x)
      out.push(legend())
      out.push(<h2>{adhoc.pretty(t)} survival</h2>)
      out.push(
        <Domplot
          rows={db.filter(row => row.tumor == t).map(rename_row)}
          kind="forest"
          options={opts}
        />
      )
      out.push(forest_x)
      out.push(legend())
    }
    for (const c of cells) {
      out.push(<h2>{adhoc.pretty(c)} survival</h2>)
      out.push(
        <Domplot
          rows={db.filter(row => row.cell == c)}
          kind="forest"
          options={{facet_x: 'tumor', ...opts}}
        />
      )
      out.push(forest_x)
      out.push(legend(adhoc.cell_color(c)))
    }
  }

  return <div className={classes.Right}>{ui.dummy_keys(out)}</div>
}

/**

  We used to serve the database statically as an embedded json but to
  make it possible to change it without rebuilding the frontend we get
  it from the backend.

*/
function useSplashProps(): SplashProps {
  const db0 = backend.useRequest('database') as undefined | SplashDB
  const db = db0 && db0.sort(by(row => both.indexOf(row.tumor)))

  const range = React.useMemo(() => (db ? utils.row_range(db) : undefined), [db])

  const [state, set_state_raw] = React.useState(state0)

  return {state, set_state: s => set_state_raw(fixup_state(s)), range, db}
}

export const Splash = React.memo(function Splash() {
  const splash_props = useSplashProps()
  return (
    <Dyn>
      <div className={classes.Splash}>
        <DomplotCSS />
        <Left {...splash_props} />
        <Center {...splash_props} />
        <Right {...splash_props} />
      </div>
    </Dyn>
  )
})

import stories from '@app/ui_utils/stories'

function LeftOnly() {
  return <Left {...useSplashProps()} />
}

stories(add => {
  add(<Splash />)
  add({mock: <Splash />}).wrap(backend.mock(import('./data/splash')))

  add(<LeftOnly />).wrap(backend.mock(import('./data/splash')))
})
