name: Docker Compose Build

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose images
      run: docker-compose build
