name: Backend Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install depencencies
          run: |
            python -m pip install --upgrade pip
            pip install -r api/requirements.txt
        - name: Run tests
          run: python api/test.py